name: "Multi event pipeline / workflow"

on:
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy_push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on GITHUB_BRANCH push"
        run: echo "Running on GITHUB_BRANCH push"

  deploy_pull: 
    if: github.event_name == 'pull'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on pull request"
        run: echo "Running on pull request"

  disploy_workflow_dispatch:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on workflow dispatch"
        run: echo "Running on workflow dispatch"


      