name: "Multi event pipeline / workflow"

on:
  push:
    branches:
      - master
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Running on $GITHUB_BRANCH push"
        run: echo "Running on $GITHUB_BRANCH push"

      