name: "Multi event pipeline / workflow"

on:
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Running on GITHUB_BRANCH push"
        run: echo "Running on GITHUB_BRANCH push"

  deploy_pull: 
    runs-on: ubuntu-latest
    steps:
      - name: "Running on pull request"
        run: echo "Running on pull request"


      